# the ID is mutched when all components are all matched

# the inclusion relation is
# module : module is top
# - joint : modules contain joints
#   - motor: joints contain motors
# - connector : modules contian connectors
#   - motor: connectors contain motors
# - wheel:
# - gripper:
#   - motor: grippers contain motors
# - camera:
# - depthcamera:
# - imu:
# - lidar:
# - battery:
# - solar_panel:

ms_module_msgs/ConnectorID connector_id