controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - LR0_TC
      - LR0_CT
      - LR0_FT
      - LR0_WH
      - LR1_TC
      - LR1_CT
      - LR1_FT
      - LR1_WH
      - LL0_TC
      - LL0_CT
      - LL0_FT
      - LL0_WH
      - LL1_TC
      - LL1_CT
      - LL1_FT
      - LL1_WH
      - LF0_TC
      - LF0_CT
      - LF0_FT
      - LF0_WH
      - LH0_TC
      - LH0_CT
      - LH0_FT
      - LH0_WH
    gains:
      LR0_TC:
        p: 50.0
        d: 2.0
        i: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
      LR0_CT:
        p: 50.0
        d: 2.0
        i: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
      LR0_FT:
        p: 50.0
        d: 2.0
        i: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
      LR0_WH:
        p: 50.0
        d: 2.0
        i: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
      LR1_TC:
        p: 50.0
        d: 2.0
        i: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
      LR1_CT:
        p: 50.0
        d: 2.0
        i: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
      LR1_FT:
        p: 50.0
        d: 2.0
        i: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
      LR1_WH:
        p: 50.0
        d: 2.0
        i: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
      LL0_TC:
        p: 50.0
        d: 2.0
        i: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
      LL0_CT:
        p: 50.0
        d: 2.0
        i: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
      LL0_FT:
        p: 50.0
        d: 2.0
        i: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
      LL0_WH:
        p: 50.0
        d: 2.0
        i: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
      LL1_TC:
        p: 50.0
        d: 2.0
        i: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
      LL1_CT:
        p: 50.0
        d: 2.0
        i: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
      LL1_FT:
        p: 50.0
        d: 2.0
        i: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
      LL1_WH:
        p: 50.0
        d: 2.0
        i: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
      LF0_TC:
        p: 50.0
        d: 2.0
        i: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
      LF0_CT:
        p: 50.0
        d: 2.0
        i: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
      LF0_FT:
        p: 50.0
        d: 2.0
        i: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
      LF0_WH:
        p: 50.0
        d: 2.0
        i: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
      LH0_TC:
        p: 50.0
        d: 2.0
        i: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
      LH0_CT:
        p: 50.0
        d: 2.0
        i: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
      LH0_FT:
        p: 50.0
        d: 2.0
        i: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
      LH0_WH:
        p: 50.0
        d: 2.0
        i: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0

    #gains:
    #  lr0_tc: {p: 50.,  d: 1., i: 0., i_clamp: 1., ff_velocity_scale: 0.0}
    #  lr0_ct: {p: 50.,  d: 1., i: 0., i_clamp: 1., ff_velocity_scale: 0.0}      
    #  lr0_ft: {p: 50.,  d: 1., i: 0., i_clamp: 1., ff_velocity_scale: 0.0}
    #  lr1_tc: {p: 50.,  d: 1., i: 0., i_clamp: 1., ff_velocity_scale: 0.0}
    #  lr1_ct: {p: 50.,  d: 1., i: 0., i_clamp: 1., ff_velocity_scale: 0.0}      
    #  lr1_ft: {p: 50.,  d: 1., i: 0., i_clamp: 1., ff_velocity_scale: 0.0}      
    #  ll0_tc: {p: 50.,  d: 1., i: 0., i_clamp: 1., ff_velocity_scale: 0.0} 
    #  ll0_ct: {p: 50.,  d: 1., i: 0., i_clamp: 1., ff_velocity_scale: 0.0}
    #  ll0_ft: {p: 50.,  d: 1., i: 0., i_clamp: 1., ff_velocity_scale: 0.0}
    #  ll1_tc: {p: 50.,  d: 1., i: 0., i_clamp: 1., ff_velocity_scale: 0.0}
    #  ll1_ct: {p: 50.,  d: 1., i: 0., i_clamp: 1., ff_velocity_scale: 0.0}
    #  ll1_ft: {p: 50.,  d: 1., i: 0., i_clamp: 1., ff_velocity_scale: 0.0}
      
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      
    #state_publish_rate:  25.0            # Override default
    #action_monitor_rate: 20.0
    #allow_partial_joints_goal: true
    allow_nonzero_velocity_at_trajectory_end: true

